### ISSUE TITLE
不同意 C++ 读 c-plus-plus

### ISSUE THREAD

**Issue by CheneyWong** [Windsooon/How-to-pronounce#5]
1. 没必要完全改用英语，难道 mp3 要读 m p three ？
2. 读 c jia jia 更简单，简单就是美。
3. 呼吁在合适的地方采用中文单音节替换英文多音节发音。比如加减乘除，以及数字的读法等。向全世界输出这种更简练的读法。

**Comment by Windsooon** [comment]
[Bjarne Stroustrup: Advice for C++ Developers](https://www.youtube.com/watch?v=BzphqTn1wPc)--youtube  这里有一篇C++ 之父介绍C++的视频，单词读音遵循作者或主要维护团队或国际约定读法。
